[font]
size = 17

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
[window.padding]
x = 7
y = 0

[general]
import = ["./themes/gruvbox_dark.toml"]

[terminal]
[terminal.shell]
program = "/bin/zsh"
